@startuml
title Diagrama de Sequência - Efetuar Reserva

actor EncarregadoEducacao
boundary PaginaReserva
control GestorReserva
entity Figurino
entity Reserva



EncarregadoEducacao -> PaginaReserva : acederCatalogo()
activate EncarregadoEducacao
activate PaginaReserva

PaginaReserva -> GestorReserva : solicitarFigurinosDisponiveis()
activate GestorReserva

GestorReserva -> Figurino : verificarDisponibilidade(dataInicio, dataFim)
activate Figurino
Figurino --> GestorReserva : disponibilidade
deactivate Figurino

alt figurino disponível
    GestorReserva --> PaginaReserva : apresentarFigurinosDisponiveis()
    deactivate GestorReserva

    EncarregadoEducacao -> PaginaReserva : selecionarFigurino(figurino, dataInicio, dataFim)

    PaginaReserva -> GestorReserva : efetuarReserva(figurino, dataInicio, dataFim)
    activate GestorReserva

    GestorReserva -> Reserva : criarReserva(dataInicio, dataFim)
    activate Reserva
    Reserva --> GestorReserva : reservaCriada
    deactivate Reserva

    GestorReserva -> Reserva : confirmarReserva()
    activate Reserva
    Reserva --> GestorReserva : reservaConfirmada
    deactivate Reserva

    GestorReserva --> PaginaReserva : mostrarReservaSubmetida()
    deactivate GestorReserva

    PaginaReserva --> EncarregadoEducacao : reservaSubmetidaComSucesso()

else figurino indisponível
    GestorReserva --> PaginaReserva : informarIndisponibilidade()
    deactivate GestorReserva

    PaginaReserva --> EncarregadoEducacao : mostrarMensagemIndisponivel()
deactivate PaginaReserva
deactivate EncarregadoEducacao
end




@enduml