@startuml
title Diagrama de Sequência - Registar Levantamento

actor Administrador

boundary PaginaLevantamento
control GestorReserva
entity Reserva
entity Checklist

Administrador -> PaginaLevantamento : iniciarLevantamento(reservaID)
activate Administrador
activate PaginaLevantamento

PaginaLevantamento -> GestorReserva : obterReserva(reservaID)
activate GestorReserva

GestorReserva -> Reserva : localizarReserva(reservaID)
activate Reserva
Reserva --> GestorReserva : reservaEncontrada
deactivate Reserva

GestorReserva -> Checklist : criarChecklistLevantamento(reservaID)
activate Checklist
Checklist --> GestorReserva : checklistCriada
deactivate Checklist

GestorReserva --> PaginaLevantamento : apresentarChecklist()
deactivate GestorReserva

Administrador -> PaginaLevantamento : registarEstadoInicial(figurino)
PaginaLevantamento -> GestorReserva : confirmarLevantamento()
activate GestorReserva

GestorReserva -> Reserva : registarLevantamento()
activate Reserva
Reserva --> GestorReserva : levantamentoRegistado
deactivate Reserva

GestorReserva --> PaginaLevantamento : levantamentoConfirmado()
deactivate GestorReserva

PaginaLevantamento --> Administrador : levantamentoConcluido()

deactivate PaginaLevantamento
deactivate Administrador

@enduml